spring:
  datasource:
    url: jdbc:mysql://39.108.60.205:3306/admin?allowMultiQueries=true&autoReconnect=true
    username: root
    password: Wkk%#eREWUeqseAss*(4saw
    driverClassName: com.mysql.jdbc.Driver
    #pool
    dbcp2:
      # 连接初始值，连接池启动时创建的连接数量的初始值  默认值是0 -->
      initial-size: 20
      # 最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请  默认值是0 -->
      min-idle: 20
      # 最大空闲值.当经过一个高峰时间后，连接池可以慢慢将已经用不到的连接慢慢释放一部分，一直减少到maxIdle为止 ，0时无限制  默认值是8 -->
      max-idle: 100
      # 连接池的最大值，同一时间可以从池分配的最多连接数量，0时无限制   默认值是8 -->
      max-total: 100
      max-wait-millis: 10000
      # 默认 true
      test-on-borrow: true
      # 默认 false
      test-on-return: false
      # 默认 false
      test-on-create: false
      # 默认 false
      remove-abandoned-on-borrow: false
      validation-query: select 1 from DUAL
  #redis
  redis:
    host: localhost
    password:
    port: 6379
    timeout: 10000
    database: 0
    pool:
      max-active: 100
      max-idle: 100
      max-wait: 30000
      min-idle: 20


#mybatis
mybatis:
  type-handlers-package: org.demon.mybatis.handler
  mapper:
    basePackage: org.demon.mapper

#\u81EA\u5B9A\u4E49 build
build:
  jwt:
    key: jwt_x_L.498&C$1@0
  #是否使用GsonResponseMessageConverter
  addConverter: true
  #转换Enum是否允许为Null
  shouldNullEnum: false
  debug:
    #是否是debug模式
    enable: true
  syncTask:
    enable: true
    timeout: 1800000
    deleteKey: false

pay:
  notify: http://39.108.60.205:8080/notify
  zny:
    uid: 308981785199
    token: f682748b586a7d3ebb129e755c64e76e
#    uid: 57752125
#    token: d334cb030f2935c306ed47454a8c18dd
    order: http://zny.39n6.cn/pay/action
    select: http://zny.39n6.cn/pay/select


